# Generated by Django 4.2.7 on 2023-11-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_filmlistmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmlistmodel',
            name='year',
        ),
    ]
