# Generated by Django 4.2.7 on 2023-11-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_countrymodel_rename_afisha_tablecoutnry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecoutnry',
            name='film',
            field=models.CharField(max_length=100, null=True, verbose_name='Название страны Афиша'),
        ),
        migrations.AlterField(
            model_name='tablecoutnry',
            name='time',
            field=models.TimeField(null=True, verbose_name='Вылет рейса'),
        ),
    ]
