# Generated by Django 4.2.7 on 2023-11-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tablecoutnry_film_alter_tablecoutnry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecoutnry',
            old_name='film',
            new_name='country',
        ),
    ]
