# Generated by Django 4.2.7 on 2023-11-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_film_tablecoutnry_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablecoutnry',
            name='area',
        ),
    ]
